config/routes.rb
Rails.application.routes.draw do
  get 'operations/ads_list', to: "operations#ads_list"
  get 'operations/users_list', to: "operations#users_list"
  # Root
  root to: "app#index"

  # Static Pages
  get "tos", to: "app#tos"
  get "privacy", to: "app#privacy"

  # Devise
  devise_for :users,
    path: "",
    path_names: {
      sign_in: "login",
      sign_out: "logout",
      registration: "signup",
      sign_up: "",
    },
    controllers: {
      sessions: "users/sessions",
      passwords: "users/passwords",
      registrations: "users/registrations",
      confirmations: "users/confirmations",
      omniauth_callbacks: "users/omniauth_callbacks",
    }

  # User
  resources :users, only: [:show, :destroy] do
    get "image", to: "users#show_image"
  end
  get "user/destroy_confirmation", to: "users#destroy_confirmation"

  # User Password
  resource :pass, only: [:new, :create, :edit, :update]

  # Advertisement Image
  resources :advertisements, only: [:index, :create, :destroy] do
    get "image", to: "advertisements#show_image"
  end

  # Display
  resources :displays, only: [:show]

  # Contact
  resource :contact, only: [:show, :create]

  # Review
  resource :review, only: [:create]

  # Checkin
  get "checkin/:id", to: "checkins#checkin", as: "checkin"
  get "checkout/:id", to: "checkins#checkout", as: "checkout"
  get "checkout_all", to: "checkins#checkout_all", as: "checkout_all"

  # Admin Pages
  ActiveAdmin.routes(self)

  # Web Mailer
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Exception
  get "*not_found", to: "application#routing_error"
  post "*not_found", to: "application#routing_error"
end

app/controllers/passes_controller.rb
class PassesController < ApplicationController
  # Authentication
  before_action :valid_password

  # New
  def new
    @user = User.new
  end

  # Create
  def create
    @user = current_user

    @user.assign_attributes(password_params)
    if @user.save
      sign_in(:user, @user, bypass: true)
      flash[:success] = "パスワードを登録しました"
      redirect_to root_path
    else
      render :new
    end
  end

  # Edit
  def edit
    @user = User.new
  end

  # Update
  def update
    @user = current_user

    if params[:user][:current_password].present?
      if @user.valid_password?(params[:user][:current_password])
        @user.assign_attributes(password_params)
        if @user.save
          sign_in(:user, @user, bypass: true)
          flash[:success] = "パスワードを変更しました"
          redirect_to root_path
        else
          render :edit
        end
      else
        @user.errors.add(:current_password, :wrong)
        render :edit
      end
    else
      @user.errors.add(:current_password, :blank)
      render :edit
    end
  end

  private
    # Valid Password?
    def valid_password
      authorize Pass
    end

    # Params
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/views/passes/edit.html.erb
<section>
  <div class="wrap">
    <h2>パスワード変更</h2>

    <%= form_for @user, url: pass_path, html: { method: :put } do |f| %>
      <%= render "devise/shared/error_messages", resource: @user %>

      <div class="field">
        <%= f.label :current_password %><br />
        <%= f.password_field :current_password, autocomplete: "current-password" %>
      </div>

      <div class="field">
        新しい<%= f.label :password %><em>(<%= User.password_length.min %>文字以上)</em><br />
        <%= f.password_field :password, autocomplete: "new-password" %>
      </div>

      <div class="field">
        新しい<%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
      </div>

      <div class="center_buttons">
        <%= link_to :back, class:"button_area_blue action_button_side" do%>
          <span class="material-icons">backspace</span>
          キャンセル
        <% end %>
        <%= button_tag :type => "submit", :class =>"button_area" do %>
          <span class="material-icons">save</span>
          変更する
        <% end %>
      </div>
    <% end %>
  </div>

  <%= render "devise/shared/assets" %>
</section>

app/views/passes/new.html.erb
<section>
  <div class="wrap">
    <h2>パスワード登録</h2>

    <%= form_for @user, url: pass_path, html: { method: :post } do |f| %>
      <%= render "devise/shared/error_messages", resource: @user %>

      <div class="field">
        新しい<%= f.label :password %><em>(<%= User.password_length.min %>文字以上)</em><br />
        <%= f.password_field :password, autocomplete: "new-password" %>
      </div>

      <div class="field">
        新しい<%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
      </div>

      <div class="center_buttons">
        <%= f.submit "パスワードを登録する", class:"button_area" %>
      </div>
    <% end %>
  </div>

  <%= render "devise/shared/assets" %>
</section>