config/routes.rb
Rails.application.routes.draw do
  get 'operations/ads_list', to: "operations#ads_list"
  get 'operations/users_list', to: "operations#users_list"
  # Root
  root to: "app#index"

  # Static Pages
  get "tos", to: "app#tos"
  get "privacy", to: "app#privacy"

  # Devise
  devise_for :users,
    path: "",
    path_names: {
      sign_in: "login",
      sign_out: "logout",
      registration: "signup",
      sign_up: "",
    },
    controllers: {
      sessions: "users/sessions",
      passwords: "users/passwords",
      registrations: "users/registrations",
      confirmations: "users/confirmations",
      omniauth_callbacks: "users/omniauth_callbacks",
    }

  # User
  resources :users, only: [:show, :destroy] do
    get "image", to: "users#show_image"
  end
  get "user/destroy_confirmation", to: "users#destroy_confirmation"

  # User Password
  resource :pass, only: [:new, :create, :edit, :update]

  # Advertisement Image
  resources :advertisements, only: [:index, :create, :destroy] do
    get "image", to: "advertisements#show_image"
  end

  # Display
  resources :displays, only: [:show]

  # Contact
  resource :contact, only: [:show, :create]

  # Review
  resource :review, only: [:create]

  # Checkin
  get "checkin/:id", to: "checkins#checkin", as: "checkin"
  get "checkout/:id", to: "checkins#checkout", as: "checkout"
  get "checkout_all", to: "checkins#checkout_all", as: "checkout_all"

  # Admin Pages
  ActiveAdmin.routes(self)

  # Web Mailer
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Exception
  get "*not_found", to: "application#routing_error"
  post "*not_found", to: "application#routing_error"
end

app/models/user.rb
class User < ApplicationRecord
  # Include
  include SnsAuthModule
  include ProfileUpdateModule

  # Rollify
  rolify

  # Devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: %i[google_oauth2 twitter facebook]

  # Attribute
  attr_accessor :current_password
  attr_accessor :profimg_temp
  attr_accessor :create_by_sns

  enum  gender:  { man: 0, woman: 1, others: 2 }
  enum  personality: {
    noanswer: 0,
    INTJ_A: 1, INTJ_T: 2, INTP_A: 3, INTP_T: 4, ENTJ_A: 5, ENTJ_T: 6, ENTP_A: 7, ENTP_T: 8,
    INFJ_A: 9, INFJ_T: 10, INFP_A: 11, INFP_T: 12, ENFJ_A: 13, ENFJ_T: 14, ENFP_A: 15, ENFP_T: 16,
    ISTJ_A: 17, ISTJ_T: 18, ISFJ_A: 19, ISFJ_T: 20, ESTJ_A: 21, ESTJ_T: 22, ESFJ_A: 23, ESFJ_T: 24,
    ISTP_A: 25, ISTP_T: 26, ISFP_A: 27, ISFP_T: 28, ESTP_A: 29, ESTP_T: 30, ESFP_A: 31, ESFP_T: 32
  }

  # Validation
  validates :comment, length:{maximum: 40}
  validates :name, presence:true, length:{maximum: 24}
  validates :password, presence: { if: :current_password }

  # CheckinRecord -> Shop
  has_many :checkin_record, dependent: :delete_all
  has_many :checking_shop, through: :checkin_record, source: :shop

  # Interest -> Tag
  has_many :interest, dependent: :delete_all
  has_many :tag, through: :interest

  # Color
  belongs_to :color

  # My Shop
  belongs_to :shop, optional: true

  # SNS Credentials
  has_many :sns_credentials, dependent: :destroy

  # Has Password?
  def has_password?
    return encrypted_password.present?
  end

  # Get Record Checked In
  def get_checkin_record
    checkin_record.where(check_in: 'in').first
  end

  # Get Shop Checked In
  def get_checkin_shop
    get_checkin_record.shop
  end

  # Check In?
  def check_in?
    get_checkin_record ? true : false
  end

  # Check In
  def checkin(shop_id)
    unless check_in?
      if not has_checkined_today? shop_id
        checkin_point = Shop.find(shop_id).checkin_point
        set_point checkin_point
      end

      checkin_record.create(user_id: self.id, shop_id: shop_id)
    end
  end

  # Check Out
  def checkout
    if check_in?
      get_checkin_record.checkout
    end
  end

  private

    # Set pecific points to user
    def set_point(point)
      self.point += point
      self.save
    end

    # Has already checkined today?
    def has_checkined_today?(shop_id)
      checkin_record.where(shop_id: shop_id, created_at: Date.today.all_day).present?
    end

    # Require Password?
    def password_required?
      super && !create_by_sns
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  protected

    def after_confirmation_path_for(resource_name, resource)
      sign_in(:user, resource)
      edit_user_registration_path
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # Google
  def google_oauth2
    callback_for(:google)
  end

  # Twitter
  def twitter
    callback_for(:twitter)
  end

  # Facebook
  def facebook
    callback_for(:facebook)
  end

  # Callback Base
  def callback_for(provider)
    info = User.find_oauth(request.env["omniauth.auth"])

    if info[:new]
      sign_in(:user, info[:user])
      flash[:success] = "アカウントを登録しました。"
      redirect_to edit_user_registration_path
    else
      sign_in_and_redirect info[:user], event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    if params[:user][:profimg_temp]
      file = trans_file(params[:user][:profimg_temp])
    else
      file = File.open("./app/assets/images/noavatar.png", "r")
    end
    params[:user][:profimg] = file.read

    super

    # Add Default Role
    if resource.roles.blank?
      resource.add_role :guest
    end
  end

  def update
    if params[:user][:profimg_temp]
      file = trans_file(params[:user][:profimg_temp])
      params[:user][:profimg] = file.read
    end

    super
  end

  protected

    def update_resource(resource, params)
      resource.update_without_current_password(params)
    end

    def trans_file(file)
      bin = Base64.decode64(file)
      file = Tempfile.new('img', :encoding => 'utf8')
      file.binmode
      file << bin
      file.rewind

      return file
    end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Show
  def show
    @user = User.find(params[:id])
  end

  # Destroy
  def destroy
    @user = User.find(params[:id])
    user_name = @user.name

    # Authentication
    authorize @user

    if @user.destroy
      flash[:success] = "#{user_name}: 退会処理が完了しました"
    else
      flash[:danger] = "#{user_name}: 退会処理に失敗しました"
    end

    redirect_to root_path
  end

  # Destroy Confirmation
  def destroy_confirmation
  end

  # Show Image
  def show_image
    profimg = User.find(params[:user_id]).profimg
    send_data(profimg)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  require 'rqrcode'
  require 'rqrcode_png'
  require 'chunky_png'

  def qrcode(text)
    qr = RQRCode::QRCode.new(text)
    png = qr.as_png.resize(500,500).to_datastream
    ChunkyPNG::Image.from_datastream(png).to_data_url
  end
end

app/views/users/destroy_confirmation.html.erb
<section>
  <div class="wrap">
    <h2>退会</h2>

    <p class="p_item">本当に退会しますか？</p>
    <div class="center_buttons">
      <%= link_to "退会", user_path(current_user.id), method: "delete", class:"button_area_blue p_item", data: {
        confirm: "本当に実行しますか？",
        cancel: "キャンセル",
        commit: "退会",
      }, title: "退会確認" %>
    </div>
  </div>
</section>

app/views/users/display.html.erb
<div class="container">
  <div class="swiper-container">
    <div class="swiper-wrapper">
      <% @panels.each do |panel| %>
        <div id="prof_<%= panel[:type]%>_<%= panel[:body].id %>" class="prof_<%= panel[:type] %> swiper-slide">
          <% if panel[:type] == "user" %>
            <%= render "layouts/display_user", user: panel[:body] %>
          <% else %>
            <%= render "layouts/display_ad", ad: panel[:body] %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= stylesheet_link_tag "lib/swiper/swiper" %>
<%= stylesheet_link_tag "displays" %>

<%= javascript_include_tag "lib/swiper/swiper" %>
<%= javascript_include_tag "displays" %>

app/views/users/show.html.erb
<section>
  <div class="wrap">
    <%= link_to :back, class:"button_area_blue back_btn" do%>
      <span class="material-icons">arrow_back_ios</span>
      戻る
    <% end %>
    <div class="prof_info">
      <% if @user.has_role? "guest" %>
        <div class="show_profimg p_item">
          <div class="show_mainimgframe">
            <%= image_tag user_image_path(@user.id)%>
          </div>
        </div>
      <% end %>

      <% if user_signed_in? and @user.id == current_user.id %>
        <div class="center_buttons p_item">
          <%= link_to edit_user_registration_path, class:"button_area prof_edit_button button_side" do %>
            <span class="material-icons">edit</span>
            プロフィール編集
          <% end %>
          <% if @user.has_password? %>
            <%= link_to edit_pass_path, class:"button_area prof_edit_button button_side" do %>
              <span class="material-icons">vpn_key</span>
              パスワード変更
            <% end %>
          <% else %>
            <%= link_to new_pass_path, class:"button_area prof_edit_button button_side" do %>
              <span class="material-icons">vpn_key</span>
              パスワード登録
            <% end %>
          <% end %>
        </div>
      <% end %>

      <h2 class="p_item"><%= @user.name %></h2>

      <% if @user.comment != "" and !@user.comment.nil?%>
        <p class="alert_area_blue p_item">
          <%= @user.comment %>
        </p>
      <% end %>

      <% if user_signed_in? and (@user.id == current_user.id or (current_user.has_role? :staff and current_user.shop_id == @user.shop_id) or current_user.has_role? :admin) %>
        <p class="p_item"><span class="material-icons">mail_outline</span><b>メールアドレス </b><%= @user.email %></p>
      <% end %>

      <% if not @user.has_role? "admin" %>
        <% if @user.shop.present? %>
          <p class="p_item"><span class="material-icons">store</span><b>マイショップ </b><%= @user.shop.name || "none" %></p>
        <% end %>

        <% if not @user.has_role? "staff" %>
          <p class="p_item"><span class="material-icons">room</span><b>所属 </b>
            <% if @user.organization != "" and !@user.organization.nil? %>
              <%= @user.organization %>
            <% else %>
              <i>未登録</i>
            <% end %>
          </p>

          <% if user_signed_in? and @user.id == current_user.id %>
            <p class="p_item"><span class="material-icons">sentiment_satisfied_alt</span><b>性別 </b><%= t("enums.user.gender.#{@user.gender || 'default'}", default: "未登録") %></p>
            <p class="p_item"><span class="material-icons">cake</span><b>生年月日 </b>
              <% if !@user.birthday.nil? %>
                <%= @user.birthday %>
              <% else %>
                <i>未登録</i>
              <% end %>
            </p>
          <% end %>

          <p class="p_item"><span class="material-icons">insert_chart_outlined</span><b>パーソナリティ </b>
            <% if  @user.personality == 'noanswer' %>
              <i><%= I18n.t("enums.user.personality.#{@user.personality}") %></i>
            <% else %>
              <%= I18n.t("enums.user.personality.#{@user.personality}") %>
            <% end %>
          </p>

          <p class="p_item"><span class="material-icons">palette</span><b>プロフィールカラー </b><%= I18n.t("enums.user.color.#{@user.color.name}") %></p>

          <% if !@user.tag.nil? and @user.tag != [] %>
            <p class="taglist_label"><span class="material-icons">local_offer</span><b>タグ</b></p>
            <div class="p_item">
              <% @user.tag.each do |tag| %>
                <div class="button_area_blue show_tag"><%= tag.name %></div>
              <% end %>
            </div>
          <% else %>
            <p class="p_item"><span class="material-icons">local_offer</span><b>タグ </b><i>未登録</i></p>
          <% end %>

          <p class="p_item"><span class="material-icons">card_giftcard</span><b>ポイント </b><%= @user.point %> pt</p>
          <% if user_signed_in? and (@user.id == current_user.id or !current_user.has_role? "guest") %>
            <p class="p_item"><span class="material-icons">send</span><b>メールの受信設定 </b><%= @user.receiving_email ? "受信する" : "受信しない" %></p>
          <% end %>
        <% end %>
      <% end %>
      <% if current_user.has_role? :staff and @user.check_in? and current_user.shop.id == @user.get_checkin_shop.id %>
        <div class="center_buttons">
          <%= link_to "チェックアウト", checkout_url(@user.id), class:"button_area prof_edit_button", data: {
            confirm: "本当にチェックアウトしますか？",
            cancel: "キャンセル",
            commit: "チェックアウト"
          }, title: "チェックアウト確認" %>
        </div>
      <% end %>
    </div>
  </div>
</section>