config/routes.rb
Rails.application.routes.draw do
  get 'operations/ads_list', to: "operations#ads_list"
  get 'operations/users_list', to: "operations#users_list"
  # Root
  root to: "app#index"

  # Static Pages
  get "tos", to: "app#tos"
  get "privacy", to: "app#privacy"

  # Devise
  devise_for :users,
    path: "",
    path_names: {
      sign_in: "login",
      sign_out: "logout",
      registration: "signup",
      sign_up: "",
    },
    controllers: {
      sessions: "users/sessions",
      passwords: "users/passwords",
      registrations: "users/registrations",
      confirmations: "users/confirmations",
      omniauth_callbacks: "users/omniauth_callbacks",
    }

  # User
  resources :users, only: [:show, :destroy] do
    get "image", to: "users#show_image"
  end
  get "user/destroy_confirmation", to: "users#destroy_confirmation"

  # User Password
  resource :pass, only: [:new, :create, :edit, :update]

  # Advertisement Image
  resources :advertisements, only: [:index, :create, :destroy] do
    get "image", to: "advertisements#show_image"
  end

  # Display
  resources :displays, only: [:show]

  # Contact
  resource :contact, only: [:show, :create]

  # Review
  resource :review, only: [:create]

  # Checkin
  get "checkin/:id", to: "checkins#checkin", as: "checkin"
  get "checkout/:id", to: "checkins#checkout", as: "checkout"
  get "checkout_all", to: "checkins#checkout_all", as: "checkout_all"

  # Admin Pages
  ActiveAdmin.routes(self)

  # Web Mailer
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Exception
  get "*not_found", to: "application#routing_error"
  post "*not_found", to: "application#routing_error"
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
  # Validation
  validates :sponsor, presence: true, length: { maximum: 24 }
  validates :email, presence: true
  validates :adimg, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :placed_shop, presence: true
  validates_with StartDateValidator
  validates_with EndDateValidator

  # AdContract -> Shop
  has_many :ad_contract, dependent: :delete_all
  has_many :placed_shop, through: :ad_contract, source: :shop

  # Nest Create
  accepts_nested_attributes_for :ad_contract, allow_destroy: true
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  # Authentication
  before_action :authorize_staff

  # Index
  def index
    @ad = Advertisement.new
  end

  # Create
  def create
    if params[:advertisement][:adimg]
      params[:advertisement][:adimg] = params[:advertisement][:adimg].read
    end

    @ad = Advertisement.new(advertisement_params)

    if @ad.save
      flash[:success] = "広告の登録を受け付けました"
      redirect_to root_path
    else
      render :index
    end
  end

  # Destroy
  def destroy
    @ad = Advertisement.find(params[:id])

    if @ad.destroy
      flash[:success] = "削除完了しました"
    else
      flash[:danger] = "削除に失敗しました"
    end

    redirect_to :controller => 'operations', :action => 'ads_list'
  end

  # Show Image
  def show_image
    adimg = Advertisement.find(params[:advertisement_id]).adimg
    send_data(adimg)
  end

  private
    # Authorize
    def authorize_staff
      authorize User
    end

    # Params
    def advertisement_params
      params.require(:advertisement).permit(:sponsor, :email, :adimg, :url, :start_date, :end_date, { placed_shop_ids: [] })
    end
end

app/views/advertisements/index.html.erb
<section>
  <div class="wrap">
    <h2>広告登録フォーム</h2>

    <%= form_with model: @ad, url: advertisements_path, local: true, class: "ad_form" do |f| %>
      <%= render "devise/shared/error_messages", resource: @ad %>

      <div class="field">
        <%= f.label :sponsor %><i>(16文字以内)</i><br />
        <%= f.text_field :sponsor, autocomplete: "name", autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autocomplete: "email" %>
      </div>

      <div class="field">
        <%= f.label :url %><i>(任意)</i><br />
        <%= f.text_field :url, autocomplete: "url" %>
      </div>

      <div class="field">
        <p>掲載する店舗を選択してください<i>(複数選択可)</i></p>
        <%= f.collection_check_boxes :placed_shop_ids, Shop.all, :id, :name do |s| %>
          <%= s.check_box + s.label{s.text} %>
        <% end %>
      </div>

      <div class="field">
        <%= f.label :start_date %><br />
        <%= f.date_select :start_date, prompt: "--", use_month_numbers: true, selected:Time.now, start_year: Time.now.year, end_year: Time.now.year + 2 %>
      </div>

      <div class="field">
        <%= f.label :end_date %><br />
        <%= f.date_select :end_date, prompt: "--", use_month_numbers: true, selected:Time.now.since(7.days), start_year: Time.now.year, end_year: Time.now.year + 2 %>
      </div>

      <div class="field">
        <%= f.label :adimg, class:"button_area_blue" %><br />
        <%= f.file_field :adimg, accept: "image/jpg, image/jpeg, image/png, image/gif" %>
        <div class="ad_form_preview"></div>
      </div>

      <div class="center_buttons">
        <div class="actions">
          <%= f.submit "送信", class:"button_area" %>
        </div>
      </div>
    <% end %>
  </div>
</section>

<%= javascript_include_tag "form_img_preview" %>

app/views/advertisements/list.html.erb
<section>
  <div class="wrap">
    <h2>広告一覧</h2>
    <% @advertisements.each do |ad| %>
        <img src=<%= advertisement_image_path(ad.id) %>>
    <% end %>
  </div>
</section>

app/views/advertisements/new.html.erb
<section>
  <div class="wrap">
    <h2>広告登録フォーム</h2>

    <%= form_with model: @ad, url: advertisement_path, local: true, class:"ad_form" do |f| %>
      <%= render "devise/shared/error_messages", resource: @ad %>

      <div class="field">
        <%= f.label :sponsor %><i>(16文字以内)</i><br />
        <%= f.text_field :sponsor, autocomplete: "name", autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autocomplete: "email" %>
      </div>

      <div class="field">
        <%= f.label :url %><i>(任意)</i><br />
        <%= f.text_field :url, autocomplete: "url" %>
      </div>

      <div class="field">
        <p>掲載する店舗を選択してください<i>(複数選択可)</i></p>
        <%= f.collection_check_boxes :placed_shop_ids, Shop.all, :id, :name do |s| %>
          <%= s.check_box + s.label{s.text} %>
        <% end %>
      </div>

      <div class="field">
        <%= f.label :start_date %><br />
        <%= f.date_select :start_date, prompt: "--", use_month_numbers: true, selected:Time.now, start_year: Time.now.year, end_year: Time.now.year + 2 %>
      </div>

      <div class="field">
        <%= f.label :end_date %><br />
        <%= f.date_select :end_date, prompt: "--", use_month_numbers: true, selected:Time.now.since(7.days), start_year: Time.now.year, end_year: Time.now.year + 2 %>
      </div>

      <div class="field">
        <%= f.label :adimg, class:"button_area_blue" %><br />
        <%= f.file_field :adimg, accept: "image/jpg, image/jpeg, image/png, image/gif" %>
        <div class="ad_form_preview"></div>
      </div>

      <div class="center_buttons">
        <div class="actions">
          <%= f.submit "送信", class:"button_area" %>
        </div>
      </div>
    <% end %>
  </div>
</section>
<%= javascript_include_tag "form_img_preview" %>