config/routes.rb
Rails.application.routes.draw do
  get 'operations/ads_list', to: "operations#ads_list"
  get 'operations/users_list', to: "operations#users_list"
  # Root
  root to: "app#index"

  # Static Pages
  get "tos", to: "app#tos"
  get "privacy", to: "app#privacy"

  # Devise
  devise_for :users,
    path: "",
    path_names: {
      sign_in: "login",
      sign_out: "logout",
      registration: "signup",
      sign_up: "",
    },
    controllers: {
      sessions: "users/sessions",
      passwords: "users/passwords",
      registrations: "users/registrations",
      confirmations: "users/confirmations",
      omniauth_callbacks: "users/omniauth_callbacks",
    }

  # User
  resources :users, only: [:show, :destroy] do
    get "image", to: "users#show_image"
  end
  get "user/destroy_confirmation", to: "users#destroy_confirmation"

  # User Password
  resource :pass, only: [:new, :create, :edit, :update]

  # Advertisement Image
  resources :advertisements, only: [:index, :create, :destroy] do
    get "image", to: "advertisements#show_image"
  end

  # Display
  resources :displays, only: [:show]

  # Contact
  resource :contact, only: [:show, :create]

  # Review
  resource :review, only: [:create]

  # Checkin
  get "checkin/:id", to: "checkins#checkin", as: "checkin"
  get "checkout/:id", to: "checkins#checkout", as: "checkout"
  get "checkout_all", to: "checkins#checkout_all", as: "checkout_all"

  # Admin Pages
  ActiveAdmin.routes(self)

  # Web Mailer
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Exception
  get "*not_found", to: "application#routing_error"
  post "*not_found", to: "application#routing_error"
end

app/models/ad_contract.rb
class AdContract < ApplicationRecord
  # Advertisement <-> Shop
  belongs_to :advertisement
  belongs_to :shop
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
  # Validation
  validates :sponsor, presence: true, length: { maximum: 24 }
  validates :email, presence: true
  validates :adimg, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :placed_shop, presence: true
  validates_with StartDateValidator
  validates_with EndDateValidator

  # AdContract -> Shop
  has_many :ad_contract, dependent: :delete_all
  has_many :placed_shop, through: :ad_contract, source: :shop

  # Nest Create
  accepts_nested_attributes_for :ad_contract, allow_destroy: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include ActiveModel::Validations

  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    generate_public_uid generator: PublicUid::Generators::HexStringSecureRandom.new(16)
end

app/models/category.rb
class Category < ApplicationRecord
  # Tag
  has_many :tag
end

app/models/checkin_record.rb
class CheckinRecord < ApplicationRecord
  # Attribute
  enum  check_in:  { out: false, in: true }

  # User <-> Shop
  belongs_to :user
  belongs_to :shop

  # Check Out
  def checkout
    update_attributes(check_in: 'out')
  end
end

app/models/color.rb
class Color < ApplicationRecord
  # User
  has_many :user
end

app/models/contact.rb
class Contact < ApplicationRecord
  # Validation
  validates :name, presence: true, length: { maximum: 24 }
  validates :email, presence: true
  validates :message, presence: true, length: { maximum: 600 }
end

app/models/interest.rb
class Interest < ApplicationRecord
  # User <-> Tag
  belongs_to :user
  belongs_to :tag
end

app/models/pass.rb
class Pass < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  # Validation
  validates :resource_type, inclusion: { in: Rolify.resource_types }, allow_nil: true

  # User
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, polymorphic: true, optional: true

  scopify
end

app/models/shop.rb
class Shop < ApplicationRecord
  # CheckinRecord -> User
  has_many :checkin_record, dependent: :delete_all
  has_many :checkined_user, through: :checkin_record, source: :user

  # AdContract -> Advertisement
  has_many :ad_contract, dependent: :delete_all
  has_many :advertisement, through: :ad_contract

  # My User
  has_many :user

  # Get Users Checked In
  def get_checkin_users(user_id=nil)
    users = checkined_user.joins(:checkin_record).where('checkin_records.check_in', 'in').order('checkin_records.created_at DESC').uniq
    if user_id
      users.select{ |user| user[:id] == user_id } + users.select{ |user| user[:id] != user_id }
    else
      users
    end
  end

  # Get Users My Shoped
  def get_myshoped_users
    user.joins(:roles).where(roles: {name: "guest"})
  end

  # Get Staffs
  def get_staffs
    user.joins(:roles).where(roles: {name: "staff"})
  end

  # Get Advertisements within publication period
  def get_ads_within_period
    advertisement.where("start_date <= ? and end_date >= ?", Date.today, Date.today)
  end
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  # User
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  # Interest -> User
  has_many :interest, dependent: :delete_all
  has_many :user, through: :interest

  # Category
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include
  include SnsAuthModule
  include ProfileUpdateModule

  # Rollify
  rolify

  # Devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: %i[google_oauth2 twitter facebook]

  # Attribute
  attr_accessor :current_password
  attr_accessor :profimg_temp
  attr_accessor :create_by_sns

  enum  gender:  { man: 0, woman: 1, others: 2 }
  enum  personality: {
    noanswer: 0,
    INTJ_A: 1, INTJ_T: 2, INTP_A: 3, INTP_T: 4, ENTJ_A: 5, ENTJ_T: 6, ENTP_A: 7, ENTP_T: 8,
    INFJ_A: 9, INFJ_T: 10, INFP_A: 11, INFP_T: 12, ENFJ_A: 13, ENFJ_T: 14, ENFP_A: 15, ENFP_T: 16,
    ISTJ_A: 17, ISTJ_T: 18, ISFJ_A: 19, ISFJ_T: 20, ESTJ_A: 21, ESTJ_T: 22, ESFJ_A: 23, ESFJ_T: 24,
    ISTP_A: 25, ISTP_T: 26, ISFP_A: 27, ISFP_T: 28, ESTP_A: 29, ESTP_T: 30, ESFP_A: 31, ESFP_T: 32
  }

  # Validation
  validates :comment, length:{maximum: 40}
  validates :name, presence:true, length:{maximum: 24}
  validates :password, presence: { if: :current_password }

  # CheckinRecord -> Shop
  has_many :checkin_record, dependent: :delete_all
  has_many :checking_shop, through: :checkin_record, source: :shop

  # Interest -> Tag
  has_many :interest, dependent: :delete_all
  has_many :tag, through: :interest

  # Color
  belongs_to :color

  # My Shop
  belongs_to :shop, optional: true

  # SNS Credentials
  has_many :sns_credentials, dependent: :destroy

  # Has Password?
  def has_password?
    return encrypted_password.present?
  end

  # Get Record Checked In
  def get_checkin_record
    checkin_record.where(check_in: 'in').first
  end

  # Get Shop Checked In
  def get_checkin_shop
    get_checkin_record.shop
  end

  # Check In?
  def check_in?
    get_checkin_record ? true : false
  end

  # Check In
  def checkin(shop_id)
    unless check_in?
      if not has_checkined_today? shop_id
        checkin_point = Shop.find(shop_id).checkin_point
        set_point checkin_point
      end

      checkin_record.create(user_id: self.id, shop_id: shop_id)
    end
  end

  # Check Out
  def checkout
    if check_in?
      get_checkin_record.checkout
    end
  end

  private

    # Set pecific points to user
    def set_point(point)
      self.point += point
      self.save
    end

    # Has already checkined today?
    def has_checkined_today?(shop_id)
      checkin_record.where(shop_id: shop_id, created_at: Date.today.all_day).present?
    end

    # Require Password?
    def password_required?
      super && !create_by_sns
    end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  # Not Authentication
  skip_before_action :authenticate_user!

  # Index
  def index
    @shops = Shop.all
  end

  # Terms of Service
  def tos
    render layout: "another_window"
  end

  # Privacy Policy
  def privacy
    render layout: "another_window"
  end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  require 'rqrcode'
  require 'rqrcode_png'
  require 'chunky_png'

  def qrcode(text)
    qr = RQRCode::QRCode.new(text)
    png = qr.as_png.resize(500,500).to_datastream
    ChunkyPNG::Image.from_datastream(png).to_data_url
  end
end

app/views/app/index.html.erb
<section>
  <div class="wrap">
    <% flash.each do |key, value| %>
      <div class="alert_area">
        <p class="alert alert-<%= key %>">
          <%= value.html_safe %>
        </p>
      </div>
    <% end %>

    <% if user_signed_in? %>
      <% if current_user.has_role? :admin %>
        <div class="alert_area">
          <p class="p_item">管理者アカウント「<%= current_user.name %>」でサインインしています。</p>
          <p class="p_item">一般スタッフの方はスタッフアカウントでサインインしてください。</p>
          <p>システム管理を行うためには「管理画面」を開いてください。</p>
        </div>
      <% end %>
      <% if current_user.has_role? :staff %>
        <div class="alert_area_blue">
          <p class="p_item"><%= current_user.shop.name %>スタッフアカウント「<%= current_user.name %>」でサインインしています。</p>
          <p class="p_item">顧客の入退店時に顧客のQRコードを読み込んでください。</p>
          <p class="p_item">チェックアウト処理は顧客のプロフィール画面からも行えます。</p>
          <p>全員をチェックアウトさせる時は本ページ下部の「閉店処理」を押してください。</p>
        </div>
      <% end %>

      <% if current_user.check_in? or current_user.has_role? :staff %>
        <% if current_user.has_role? :guest %>
          <% current_shop = current_user.get_checkin_shop %>
        <% else %>
          <% current_shop = current_user.shop %>
        <% end %>

        <% if !current_shop.get_checkin_users.empty? %>
          <p><span class="material-icons">supervisor_account</span>現在「
            <% if current_user.has_role? :guest %>
              <%= current_user.get_checkin_shop.name %>
            <% else %>
              <%= current_user.shop.name %>
            <% end %>
          」にチェックインしているユーザ</p>
          <p class="explain">アイコンをタップしてプロフィールを確認</p>
          <ul class="prof_list top_margin">
            <% current_shop.get_checkin_users(current_user.id).each do |user| %>
              <li class="prof_list_item ellipsis">
                <%= link_to user_path(user.id) do %>
                  <div class="list_profimg_body">
                    <div class="list_mainimgframe">
                      <% if user.id == current_user.id %>
                        <%= image_tag user_image_path(current_user.id), class: "border_img" %>
                      <% else %>
                        <%= image_tag user_image_path(user.id) %>
                      <% end %>
                    </div>
                  </div>
                  <div class="clearfix"></div>
                  <p class="list_profname"><%= user.name %></p>
                <% end %>
              </li>
            <% end %>
          </ul>
          <div class="clearfix bottom_margin"></div>
        <% else %>
          <p class="alert_area_blue p_item">表示されるユーザがいません</p>
        <% end %>
      <% end %>

      <% if current_user.has_role? :admin or current_user.has_role? :staff %>
        <div class="center_buttons">
          <% if current_user.has_role? :admin %>
            <%= link_to admin_root_path, target: "_blank" , class:"button_area button_side p_item" do%>
              <span class="material-icons">build</span>
              管理画面
            <% end %>
            <% @shops.each do |shop| %>
              <%= link_to display_path(shop.id), target: "_blank" , class:"button_area button_side p_item" do %>
                <span class="material-icons">tv</span>
                <%= shop.name %>
              <% end %>
            <% end %>
          <% end %>
          <% if current_user.has_role? :staff %>
            <%= link_to display_path(current_user.shop.id), target: "_blank" , class:"button_area button_side p_item" do %>
              <span class="material-icons">tv</span>
              <%=current_user.shop.name%>
            <% end %>
          <% end%>
        </div>
      <% end %>

      <div class="center_buttons">
        <%= link_to user_path(current_user.id), class:"button_area_blue p_item" do %>
          <span class="material-icons">account_box</span>
          プロフィール確認
        <% end %>
      </div>
      <div class="center_buttons">
        <%= link_to books_path, class:"button_area_blue p_item" do %>
          <span class="material-icons">menu_book</span>
          デジタルコンテンツ
        <% end %>
      </div>

      <% if current_user.check_in? %>
        <div class="img_center">
          <p class="qrcode_text">Checkout QR</p>
          <%= image_tag qrcode(checkout_url(current_user.id)), class: "qrcode" %>
        </div>
      <% else %>
        <div class="img_center">
          <p class="qrcode_text">Checkin QR</p>
          <%= image_tag qrcode(checkin_url(current_user.id)), class: "qrcode" %>
        </div>
      <% end %>

      <div class="center_buttons smltopmargin">
        <%= link_to "サインアウト", destroy_user_session_path, method: :delete ,class:"button_area" %>
      </div>

      <% if current_user.has_role? :staff %>
        <div class="center_buttons smltopmargin">
          <%= link_to "閉店処理", checkout_all_path, class:"button_area_blue button_side p_item", data: {confirm: "本当に実行しますか？"} %>
        </div>
      <% end %>

    <% else %>
      <div class="center_buttons">
        <%= link_to "サインイン", new_user_session_path , class:"button_area button_side" %>
        <%= link_to "サインアップ", new_registration_path(User) , class:"button_area_blue" %>
      </div>
    <% end %>
  </div>
</section>

<% if !user_signed_in? %>
  <%= render "lp/lp_v1" %>
<% end %>

app/views/app/privacy.html.erb
<section>
  <div class="wrap">
    <h2>プライバシーポリシー</h2>

    <div class="p_item">
      <p>当団体は、個人情報が重要な財産（法益）であると認識しております。また、これを適切に管理し保護することが、団体としての社会的責任であると考えております。お取引先様、当社役員・従業員等の個人情報の取り扱いにつき基本方針を定めました。当団体は、本方針を遵守し、個人情報の保護に努めることを宣言いたします。</p>
    </div>

    <div class="p_item">
      <h3>1. 個人情報保護に関する法令およびその他の規範の遵守</h3>
      <p>当団体は、個人情報の保護に関係する日本の法令その他の規範、ガイドラインを遵守いたします。</p>
    </div>

    <div class="p_item">
      <h3> 2. 個人情報の定義</h3>
      <p>
        本方針に掲げる「個人情報」とは、生存する個人に関する以下の情報をいいます。
      </p>
      <p>
        (1)当該情報に含まれる氏名、生年月日、その他の記述等により特定の個人を識別できるもの
      </p>
      <p>
        (2)他の情報と容易に照合することができ、それにより特定の個人を識別することができることとなるもの
      </p>
    </div>

    <div class="p_item">
      <h3>3. 個人情報の入手</h3>
      <p>
        当団体は、個人情報を適法かつ公正な手段により取得いたします。また、入手の際にはあらかじめその目的と利用範囲をお知らせいたします。
      </p>
    </div>

    <div class="p_item">
      <h3>4. 個人情報の利用</h3>
      <p>
        当社は、ご提供頂いた個人情報の利用につき、あらかじめお知らせまたは公表した利用目的の範囲を守ります。
      </p>
    </div>

    <div class="p_item">
      <h3>5. 個人情報の提供</h3>
      <p>
        (1)当団体は、利用目的の範囲内で、個人情報を取り扱う業務を委託することがあります。その際は委託先の管理能力を十分検討し、個人情報に関する取り決めを行い、監督し、個人情報の安全管理を徹底いたします。
      </p>
      <p>
        (2)当団体は、個人情報をご本人の同意なしに業務委託先以外の第三者に開示・提供することはありません。ただし、法令により、または裁判所、警察等の公的機関から開示を求められた場合には、ご本人の同意なく個人情報を開示・提供することがあります。
      </p>
    </div>

    <div class="p_item">
      <h3>6. 個人情報のお問い合せの対応</h3>
      <p>
        当団体が管理している個人情報に関して、ご本人から開示・訂正・利用停止あるいは消去等のお申し出があったときは、以下の場合を除き、ご本人であることを確認したうえで、必要な対応をいたします。
      </p>
      <p>
        (1)ご本人または第三者の生命、身体、財産その他の権利利益を害するおそれがある場合
      </p>
      <p>
        (2)当団体の業務の適正な実施に著しい支障を及ぼすおそれがある場合
      </p>
      <p>
        (3)他の法令に違反することとなる場合
      </p>
    </div>
  </div>
</section>

app/views/app/tos.html.erb
<section>
  <div class="wrap">
    <h2>利用規約</h2>

    <p class="p_item">
      本サービスではユーザのプロフィール情報や来店履歴などを収集します。本サービスで収集されたデータはサービス関係者らがサービス改善や研究のために活用・公表される場合があります。なお、データが公表される際は個人の特定を防いだ上で実施されます。
    </p>
    <p class="p_item">
      メールアドレスなどの個人情報以外のプロフィールに登録された情報は登録された名前を含み、他ユーザが閲覧することがあります。ご了承ください。
    </p>
    <p class="p_item">
      本サービスでチェックインした店舗がK-Displayを導入している場合、登録されているプロフィール情報の一部が店内ディスプレイにて公開されますのでご注意ください。
    </p>
    <p class="p_item">
      本サービス利用者にイベント等の告知メールを送信することがあります。
    </p>
    <p class="p_item">
      本サービス関係者は、サービス利用にあたってふさわしくない行為を行ったユーザに対して、サービス利用の停止を実施したり、弁償を求めたりする場合があります。また、本サービスの利用によってユーザがいかなる損害を被った場合でもサービス関係者は責任を負いません。
    </p>
    <p class="p_item">
      本サービスを利用するにあたって、本規約に同意したものとします。
    </p>
    <p class="p_item">
      本利用規約は不定期的に更新される場合があります。更新された場合も、サービス利用をもって規約に同意したものと見做します。今後の継続的な利用にあたりましては、都度利用規約のご確認をお願いします。
    </p>
  </div>
</section>

app/views/layouts/_display_ad.html.erb
<section class="displayprof bg_black" style="background-image: url(<%= advertisement_image_path(ad.id) %>);">
  <div class="sponsor_info_area">
    <h1 class="sponsor">Sponsored by <%= ad.sponsor %></h1>
    <% if ad.url.present? %>
      <div class="ad_qrcode_area">
        <%= image_tag qrcode(ad.url), class: "ad_qrcode" %>
      </div>
    <% end %>
  </div>
</section>

app/views/layouts/_display_user.html.erb
<section class="displayprof bg_<%= user.color.name %>">
  <div class="wrap">
    <div class="post_profimg">
      <div class="mainimgframe">
        <%= image_tag user_image_path(user.id) %>
      </div>
    </div>

    <div class="prof_body">
      <div class="under">
        <div class="multiline-text-container">
          <h1 class="prof_name multiline-text-2"><%= user.name %></h1>
        </div>
      </div>
      <div class="multiline-text-container">
        <h2 class="prof_org multiline-text-1"><span class="material-icons">room</span><%= user.organization %></h2>
      </div>
      <div class="multiline-text-container">
        <h2 class="prof_tag multiline-text">
          <% user.tag.each do |tag| %>
            #<%= tag.name %>&nbsp;
          <% end %>
        </h2>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="prof_msg multiline-text-container">
      <% if user.comment? %>
        <p class="prof_msg_body multiline-text-3"><%= user.comment %></p>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<section id="footer">
  <footer>
    <div class="wrap">
      <p class="p_item footer_link"><small><a href="https://katharsis-official.com/" target="_blank">会社情報</a></small></p>
      <p class="p_item footer_link"><small><%= link_to "利用規約", tos_path, target:"_blank" %></small></p>
      <p class="p_item footer_link"><small><%= link_to "プライバシーポリシー", privacy_path, target:"_blank" %></small></p>
      <p class="p_item footer_link"><small><%= link_to "お問い合わせ", contact_path %></small></p>
      <% if user_signed_in? and (current_user.has_role? :staff or current_user.has_role? :admin) %>
        <p class="p_item footer_link"><small><%= link_to "広告の登録", advertisements_path %></small></p>
        <p class="p_item footer_link"><small><%= link_to "広告の削除", operations_ads_list_path %></small></p>
        <p class="p_item footer_link"><small><%= link_to "ユーザ一覧", operations_users_list_path %></small></p>
      <% end %>
      <% if user_signed_in? %>
        <p class="p_item footer_link"><small><%= link_to "退会", user_destroy_confirmation_path %></small></p>
      <% end %>
      <div class="clearfix"></div>
      <p><small>&copy; 2022 Katharsis Digital Hub</small></p>
    </div>
  </footer>
</section>

app/views/layouts/_header.html.erb
<section id="header">
  <div class="headerwrap">
    <p class="header_logo">
      <%= link_to root_path do %>
        <%= image_tag "/assets/KDH_logo_header.png" %>
        Katharsis Digital Hub
      <% end %>
    </p>
  </div>
</section>

app/views/layouts/another_window.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Katharsis Digital Hub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= favicon_link_tag("favicon.ico") %>
  </head>

  <body>
    <%= yield %>
    <div class="center_buttons">
      <a href="javascript:window.close();" class="button_area_blue p_item">閉じる</a>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Katharsis Digital Hub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= favicon_link_tag("favicon.ico") %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header"%>
    <main>
      <%= yield %>
    </main>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/layouts/display.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>K-Display</title>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= favicon_link_tag("favicon.ico") %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lp/_lp.html.erb
<section class="bg_white">
  <div class="wrap">
    <h2>LP</h2>
  
    
  </div>
</section>

app/views/lp/_lp_v1.html.erb
<section class="bg_purple">
  <div class="wrap">
    <h2>Katharsis Digital Hubへようこそ</h2>
    <div class="img_center">
      <%= image_tag 'connection.png', class:"libig_img" %>
    </div>
    <p class="p_item">語りバー「Katharsis」や連盟店舗に集う人々や企業をデジタルで繋げるシステムです。</p>
    <p>メール認証のほかに、GoogleやTwitterアカウントを認証することによってもアカウントを作成頂くことが可能です。</p>
  </div>
</section>

<section class="bg_cyber_japan_network">
  <div class="wrap">
    <div class="img_center">
      <%= image_tag 'KDH_logo.png', class:"libig_img" %>
      <h1 class="catchphrase top_margin">人々や企業を繋げるデジタルとアナログが融合した空間</h1>
    </div>
  </div>
</section>

<section class="bg_purple">
  <div class="wrap">
    <h2 class="slogan">QRコードを提示してチェックイン</h2>
    <div class="img_center">
      <%= image_tag 'active.png', class:"libig_img" %>
    </div>
    <p class="p_item">チェックインするとポイントを貯めることができます。<br>
      ポイントを貯めると、様々な特典が得られる予定です。ぜひチェックインしましょう。<br>
      ポイント加算は1店舗あたり1日1回までです。</p>
    <p>退店の際にQRコードを提示するとチェックアウトすることができます。</p>

    <h2 class="slogan">店内にどんなユーザがいるのかを確認</h2>
    <div class="img_center">
      <%= image_tag 'fans.png', class:"libig_img" %>
    </div>
    <p>店内のチェックインしているユーザの情報を確認することができます。<br>
      交流したい人が見つかれば、ぜひ積極的に声をかけてみましょう。</p>

    <h2 class="slogan">K-Displayとの連携</h2>
    <div class="img_center">
      <%= image_tag 'creativity.png', class:"libig_img" %>
    </div>
    <p>K-Display設置店舗では、店内にいるチェックインしているユーザの情報がK-Displayに表示されます。<br>
      ふとした瞬間に視界に入った情報が新たな語りを生み出します。</p>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="center_buttons">
      <p class="p_item">始めるにはサインアップ</p>
      <%= link_to "サインイン", new_user_session_path , class:"button_area button_side" %>
      <%= link_to "サインアップ", new_registration_path(User) , class:"button_area_blue" %>
    </div>
  </div>
</section>